import { test, expect } from '@playwright/test';

// This command is used to create a spec file and save it as output directory in the name of codegen.spec.js
// npx playwright codegen https://opensource-demo.orangehrmlive.com/web/index.php/auth/login -o ./tests/codegen.spec.js

test('Login Test auto generated by Codegen Playwright', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('PP Amnuaydechkorn').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});