import { test, expect } from '@playwright/test';

// Here is the command to run the test on a chrome browser, not a chromium browser. This is test autogenerated through this command and subsequent steps
// npx playwright codegen https://opensource-demo.orangehrmlive.com/web/index.php/auth/login -o ./tests/codegenOnChromeBrowser.spec.js --channel=chrome

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Leave' }).click();
  await page.getByText('Entitlements').click();
  await page.getByRole('menuitem', { name: 'My Entitlements' }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('manda user').click();
  await page.getByRole('link', { name: 'My Leave' }).click();
  await page.getByText('manda user').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});


// retries through command in terminal
// npx playwright test ./tests/login.spec.js --retries=2